version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: email-db
    environment:
      POSTGRES_DB: email-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

#  psql -U <nome_do_usuário> -d <nome_do_banco_de_dados>
#  psql -U postgres -d email-db
